### ISSUE TITLE
Getting Connection Issues

### ISSUE THREAD

**Issue by Tahmid-islam** [katanaml/llm-ollama-invoice-cpu#1]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connect
ion.HTTPConnection object at 0x000002D14F01A8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Can anyone faced this problem?

**Comment by abaranovskis-redsamurai** [comment]
This seems Ollama and Windows related. You should ask on Ollama GitHub, to get better answer: https://github.com/jmorganca/ollama
